# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghal < Formula
  desc "ghal allows streaming of live GitHub Actions build logs to your terminal"
  homepage "https://github.com/aidansteele/ghal"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aidansteele/ghal/releases/download/v0.1.0/ghal_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "6c7f4c8ed322a7e2ebfbe9a3704be32cc3dd27af6e7c3e7bbf4c53550d8e1616"

      def install
        bin.install "ghal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aidansteele/ghal/releases/download/v0.1.0/ghal_0.1.0_Darwin_arm64.tar.gz"
      sha256 "be8285cb34378b9bfcc67df563c2c39c5f847b4c6755ab311d6a4b9395005e80"

      def install
        bin.install "ghal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aidansteele/ghal/releases/download/v0.1.0/ghal_0.1.0_Linux_x86_64.tar.gz"
      sha256 "5730ab2cf650acfd8931f1e8c0668eb02da07dc5b285dcb132ff6b542aabac3c"

      def install
        bin.install "ghal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aidansteele/ghal/releases/download/v0.1.0/ghal_0.1.0_Linux_arm64.tar.gz"
      sha256 "3c7e8c4ad26c1d6835d71b5d302b0205947fed10da8fd92cf354faa498190871"

      def install
        bin.install "ghal"
      end
    end
  end
end
