# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lambda < Formula
  desc "CLI for invoking AWS Lambda functions in a Unix pipeline-friendly way"
  homepage "https://github.com/aidansteele/lambda"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aidansteele/lambda/releases/download/v0.0.0/lambda_Darwin_arm64.tar.gz"
      sha256 "0c3a885f05473d47e12787079642f3452cc421b353a9da92af7a88ddfc16298d"

      def install
        bin.install "lambda"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aidansteele/lambda/releases/download/v0.0.0/lambda_Darwin_x86_64.tar.gz"
      sha256 "8c333e207a392894617f239a8e4b8ca5371437fb75d6698df38aaffb267311a2"

      def install
        bin.install "lambda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aidansteele/lambda/releases/download/v0.0.0/lambda_Linux_arm64.tar.gz"
      sha256 "6668014999adea1063682df724b37854531edbef4c042d40d1d7bd3d1abea726"

      def install
        bin.install "lambda"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aidansteele/lambda/releases/download/v0.0.0/lambda_Linux_x86_64.tar.gz"
      sha256 "451a6409890d44590b8350c0d062a067d2675cca3161e565966ebb285e53aab0"

      def install
        bin.install "lambda"
      end
    end
  end
end
