# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdsconn < Formula
  desc "rdsconn makes connecting to an AWS RDS instance inside a VPC from your laptop easier"
  homepage "https://github.com/aidansteele/rdsconn"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aidansteele/rdsconn/releases/download/v0.1.0/rdsconn_Darwin_arm64.tar.gz"
      sha256 "18c1cc756924a42e26c45afb863d2c8e0bcfe37170583bbe7697366e28db5829"

      def install
        bin.install "rdsconn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aidansteele/rdsconn/releases/download/v0.1.0/rdsconn_Darwin_x86_64.tar.gz"
      sha256 "1180b648bdc46262ad32d1ed63e576af9efe3f44713750cbb91140d46f13b026"

      def install
        bin.install "rdsconn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aidansteele/rdsconn/releases/download/v0.1.0/rdsconn_Linux_arm64.tar.gz"
      sha256 "10622a15447ed45358e93763a4bb0f8b1bfd31b0b13738693e59b21cc5a7ccd1"

      def install
        bin.install "rdsconn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aidansteele/rdsconn/releases/download/v0.1.0/rdsconn_Linux_x86_64.tar.gz"
      sha256 "fbba32eda26746b6f919f742d2c4b9bcd345de6faf93f0efb57ce22500ad8a7e"

      def install
        bin.install "rdsconn"
      end
    end
  end
end
